package com.example.mealplan.common.exception;

public enum ErrorCode {
    AUTH_DUPLICATE_EMAIL,
    AUTH_INVALID_CREDENTIALS,
    AUTH_UNAUTHORIZED,
    AUTH_FORBIDDEN,
    RESOURCE_NOT_FOUND,
    MEAL_PLAN_NOT_FOUND,
    MEAL_PLAN_DUPLICATE_DATE,
    MEAL_ENTRY_NOT_FOUND,
    VALIDATION_FAILED,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR
}
